import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Playwrite_IN } from "next/font/google";
const roboto = Roboto({
  subsets:['latin'],
  weight:['400','700'],
});


const playWrite = Playwrite_IN({
  subsets:['latin'],
  weight:['100','400'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const header = (
    <header>
      this is top of the page
    </header>
  )

  const footer = (
    <footer>
      This is the bottom of the page
    </footer>
  )
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {header}
          {children}
        {footer}
      </body>
    </html>
  );
}
